spring.application.name=productservice

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=postgreS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
