spring.application.name=userservice

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=postgreS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-timeout=30000

#logging.level.com.zaxxer.hikari=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.open-in-view=false

jwt.secret=MySuperSecretKeyForEcommerceApplication123456789123456789
jwt.access-token-expiration=30000
jwt.refresh-token-expiration=604800000
jwt.issuer=ecommerce-app
